#!/bin/bash
v="$1"
if test -n "$v"; then
  . .tox/$v/bin/activate
fi

err=0
for f in \
  global_ocean.cs32x15/grid \
  global_ocean.cs32x15/state.0000072000 \
  global_ocean.cs32x15/oceDiag.0000072000 \
  global_ocean.cs32x15/phiHyd.0000072000 \
  global_ocean.cs32x15/phiHydLow.0000072000 \
  eccov3/dic_tave.0000025920
  do
  echo "# $f"
  o="$(basename $f)"
  scripts/gluemncbig -q -o $o.nc tests/data/$f.*.nc
  ncdump -h $o.nc | grep -v build_ | grep -v MITgcm_version > $o.cdl
  ncdump $o.nc | grep -v build_ | grep -v MITgcm_version | md5sum > $o.md5
  if ! diff tests/md5/$f.cdl $o.cdl; then
    echo "Metadata doesn't match reference: $f"
    err=1
  fi
  if ! diff tests/md5/$f.md5 $o.md5; then
    echo "Checksum doesn't match reference: $f"
    err=1
  fi
done
if [ "$err" = 1 ]; then
  echo "Some comparisons failed."
  exit 1
fi
