name: Initial testing of switching to github actions for CI

# For testing do on every push
on:
  push:

jobs:
 test_report:
   runs-on: ubuntu-latest

   strategy:
     matrix:
      include:
        - exp: "tutorial_deep_convection"
          precs: "16 16"
        - exp: "isomip"
          precs: "16 16 16 16"
        - exp: "aim.5l_cs"
          precs: "14 16"

   continue-on-error: true

   steps:
   
     - name: Checkout
       uses: actions/checkout@v2.2.0

     - name: Set up compilers
       run: |
         sudo apt-get update
         sudo apt-get -qq install gfortran
     
     - name: Get a docker image and set it running (if this works!)
       run: |
         docker pull mitgcm/testreport-images:ubuntu_18_04_villon
         docker run  -v `pwd`:/MITgcm --name ubuntu_18_04-testreport -t -d mitgcm/testreport-images:ubuntu_18_04_villon /bin/bash
         
     - name: Run a test
       env: 
        MITGCM_EXP: ${{ matrix.exp }}
        MITGCM_PRECS: ${{ matrix.precs }}
       run: |
         . tools/ci/runtr.sh
 
 doc_test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v2.2.0

     - name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: 3.6

     - name: install dependencies
       run: tools/ci/install_doc_dependencies.sh

     - name: build docs
       run: |
         cd doc
         sphinx-build -a -b html -d _build_doctrees . _build/html
         sphinx-build -Wa -b html -d _build_doctrees . _build/html

